apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: cove-staging
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/danicajiao/homelab.git
        targetRevision: main
        path: apps/cove/overlays/staging
    destination:
        server: https://kubernetes.default.svc
        namespace: cove-staging
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
